/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import baseDatos.tablaClientes;
import baseDatos.tablaUsuarios;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Carlos Aravena
 */
public class ControlPersonal extends javax.swing.JFrame {
    /**
     * Creates new form ControlAcceso
     */
    tablaClientes mySQL = null;
    Connection con;
    Statement stm = null;
    ResultSet rs = null;
    
    String sql = null;
    
    String num_usuario = "", cla_usuario = "";
    String mensaje, menError;
    
    
    MantenedorPer mp;
    private int opcion;
    Principal prin;
    
    public ControlPersonal() {
        
        initComponents();
    }
    
    public void validarCampos()
    {
        if(this.jtfUsuarioPersonal.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this,
                    "Debe Ingresar N° Usuario",
                    "ERROR DE INGRESO",
                    JOptionPane.ERROR_MESSAGE);
            this.jtfUsuarioPersonal.requestFocus();
            return;
        }
        if(this.jpfClavePer.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this,
                    "Debe Ingresar Clave Usuario",
                    "ERROR DE INGRESO",
                    JOptionPane.ERROR_MESSAGE);
            this.jpfClavePer.requestFocus();
            return;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUsuarioPersonal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpfClavePer = new javax.swing.JPasswordField();
        jbtAccederPer = new javax.swing.JButton();
        jbtVolverPer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso Personal");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Acceso a Personal de Renta-Car");

        jLabel2.setText("Ingrese su R.U.T:");

        jLabel3.setText("Ingrese su Clave:");

        jbtAccederPer.setText("Acceder >>");
        jbtAccederPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAccederPerActionPerformed(evt);
            }
        });

        jbtVolverPer.setText("<< Volver");
        jbtVolverPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVolverPerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtVolverPer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtAccederPer))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jtfUsuarioPersonal)
                            .addComponent(jpfClavePer))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfUsuarioPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfClavePer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtAccederPer)
                    .addComponent(jbtVolverPer))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(432, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVolverPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVolverPerActionPerformed
        // TODO add your handling code here:
        opcion = 0;
        opcion = JOptionPane.showConfirmDialog(this,
                "¿Desea Volver?",
                "Volver a Pantalla Principal",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION)
        {
            this.setVisible(false);
            prin = new Principal();
            prin.setVisible(true);
        }
        else
        {
            if(opcion == JOptionPane.NO_OPTION)
            {
                jtfUsuarioPersonal.requestFocus();
            }
        }
    }//GEN-LAST:event_jbtVolverPerActionPerformed

    private void jbtAccederPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAccederPerActionPerformed
        // TODO add your handling code here:
        mensaje = "Acceso Aceptado";
        menError = "Acceso Denegado";
        //Lectura de datos desde el formularios
        num_usuario = jtfUsuarioPersonal.getText();
        cla_usuario= jpfClavePer.getText();
        //Validar Campos
        validarCampos();
        //Abrir Conexiones a MySQL
        tablaUsuarios mysql = new tablaUsuarios();
        java.sql.Connection cn = mysql.Conectar();
        //Seleccionar Consulta
        sql = "Select * From Usuarios where num_usuario='"+num_usuario+"';";
        //Ejecutar consulta llenando los parametros con los valores capturados
        try
        {
            java.sql.Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
            {
                String clave_usuario = rs.getString(3);
                if(clave_usuario.equalsIgnoreCase(cla_usuario))
                {
                    this.setVisible(false);
                    mp = new MantenedorPer();
                    mp.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,
                            "Clave Incorrecta",
                            "ERROR DE ACCESO",
                            JOptionPane.ERROR_MESSAGE);
                    if(clave_usuario!=cla_usuario)
                    {
                        jpfClavePer.setText("");
                        jpfClavePer.requestFocus();
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,
                        "Usuario No Existe",
                        "USUARIO INCORRECTO",
                        JOptionPane.ERROR_MESSAGE);
                jtfUsuarioPersonal.setText("");
                jtfUsuarioPersonal.requestFocus();
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,
                    "Error de Lectura de Datos");
        }
    }//GEN-LAST:event_jbtAccederPerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPersonal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtAccederPer;
    private javax.swing.JButton jbtVolverPer;
    private javax.swing.JPasswordField jpfClavePer;
    private javax.swing.JTextField jtfUsuarioPersonal;
    // End of variables declaration//GEN-END:variables
}
