/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import baseDatos.tablaPagos;
import baseDatos.tablaVehiculos;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Aravena A
 */
public class FormasPago extends javax.swing.JFrame {

    /**
     * Creates new form FormasPago
     */
    TiposPago tp;
    MantenedorPer mp;
    private DefaultTableModel modelo;
    String sql;
    private int opcion;
    public FormasPago() {
        initComponents();
        tablaPagos();
    }
    public void tablaPagos()
    {
        modelo = new DefaultTableModel();
        modelo.addColumn("RUT Cliente");
        modelo.addColumn("Nombre");
        modelo.addColumn("Forma Pago");
        modelo.addColumn("Codigo Cheque");
        modelo.addColumn("N° Cheque");
        modelo.addColumn("Banco");
        modelo.addColumn("Precio $");
        try
        {
            tablaPagos mysql = new tablaPagos();
            java.sql.Connection cn= mysql.Conectar();
            sql="Select * from Pagos";
            java.sql.Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                Object[] registro=new Object[8];
                registro[0]=rs.getString("rut_pago");
                registro[1]=rs.getString("nomCliente_pago");
                registro[2]=rs.getString("forma_pago");
                registro[3]=rs.getString("codigo_cheque");
                registro[4]=rs.getString("num_cheque");
                registro[5]=rs.getString("banco_pago");
                registro[6]=rs.getString("precio_pago");
                modelo.addRow(registro);
            }
            jTable1.setModel(modelo);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog( null,
                    "Error de Lectura de Datos");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiAgregarPago = new javax.swing.JMenuItem();
        jmiModificarPago = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiOK = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Rut Cliente ", "Nombre Cliente", "Forma de Pago", "Codigo Cheque", "Numero Cheque", "Banco", "Precio $"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Gestionar");

        jmiAgregarPago.setText("Agregar Pago");
        jmiAgregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarPagoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAgregarPago);

        jmiModificarPago.setText("Modificar Pago");
        jmiModificarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarPagoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiModificarPago);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Finalizar");

        jmiOK.setText("OK");
        jmiOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOKActionPerformed(evt);
            }
        });
        jMenu2.add(jmiOK);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(693, 286));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarPagoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        tp = new TiposPago(1);
        tp.setVisible(true);
    }//GEN-LAST:event_jmiAgregarPagoActionPerformed

    private void jmiModificarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarPagoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        tp = new TiposPago(2);
        tp.setVisible(true);
    }//GEN-LAST:event_jmiModificarPagoActionPerformed

    private void jmiOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOKActionPerformed
        // TODO add your handling code here:
        opcion = 0;
        opcion = JOptionPane.showConfirmDialog(this,
                "¿Desea Volver?",
                "VOLVER",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if(opcion == JOptionPane.YES_OPTION)
        {
            this.setVisible(false);
            mp = new MantenedorPer();
            mp.setVisible(true);
        }
        
    }//GEN-LAST:event_jmiOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormasPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormasPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormasPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormasPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormasPago().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem jmiAgregarPago;
    private javax.swing.JMenuItem jmiModificarPago;
    private javax.swing.JMenuItem jmiOK;
    // End of variables declaration//GEN-END:variables
}
