/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Carlos Aravena
 */
public class MantenedorAdm extends javax.swing.JFrame {

    /**
     * Creates new form MantenedorAdm
     */
    public MantenedorAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmbGestionarPersonal = new javax.swing.JMenu();
        jmIngresarPersonal = new javax.swing.JMenuItem();
        jmEliminarPersonal = new javax.swing.JMenuItem();
        jmbGestionarConsultas = new javax.swing.JMenu();
        jmConsultarPersonal = new javax.swing.JMenuItem();
        jmConsultarClientes = new javax.swing.JMenuItem();
        jmbSalir = new javax.swing.JMenu();
        jmFinalizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmbGestionarPersonal.setText("Gestionar Personal");

        jmIngresarPersonal.setText("Ingresar Personal");
        jmbGestionarPersonal.add(jmIngresarPersonal);

        jmEliminarPersonal.setText("Eliminar Personal");
        jmbGestionarPersonal.add(jmEliminarPersonal);

        jMenuBar1.add(jmbGestionarPersonal);

        jmbGestionarConsultas.setText("Gestionar Consultas");

        jmConsultarPersonal.setText("Consultar Registros Personal");
        jmbGestionarConsultas.add(jmConsultarPersonal);

        jmConsultarClientes.setText("Consultar Registros Clientes");
        jmbGestionarConsultas.add(jmConsultarClientes);

        jMenuBar1.add(jmbGestionarConsultas);

        jmbSalir.setText("Salir");

        jmFinalizar.setText("Finalizar");
        jmbSalir.add(jmFinalizar);

        jMenuBar1.add(jmbSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorAdm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmConsultarClientes;
    private javax.swing.JMenuItem jmConsultarPersonal;
    private javax.swing.JMenuItem jmEliminarPersonal;
    private javax.swing.JMenuItem jmFinalizar;
    private javax.swing.JMenuItem jmIngresarPersonal;
    private javax.swing.JMenu jmbGestionarConsultas;
    private javax.swing.JMenu jmbGestionarPersonal;
    private javax.swing.JMenu jmbSalir;
    // End of variables declaration//GEN-END:variables
}
