/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Aravena
 */
public class MantenedorPer extends javax.swing.JFrame {

    /**
     * Creates new form Mantenedor
     */
    IngresoClientes ic;
    SolicitudArriendo sa;
    Contrato con;
    Presupuesto pres;
    ListadoClientes lc;
    
    private int opcion;
    public MantenedorPer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmbGestionarSolicitudes = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jmIngresarClientes = new javax.swing.JMenuItem();
        jmeModificarClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmIngresarReservas = new javax.swing.JMenuItem();
        jmiModificarReservas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmCrearContratos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiCalcularPresupuesto = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmConsultarRegistros = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmbSalir = new javax.swing.JMenu();
        jmFinalizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenedor");

        jmbGestionarSolicitudes.setText("Gestionar");
        jmbGestionarSolicitudes.add(jSeparator1);

        jMenu1.setText("Clientes");

        jmIngresarClientes.setText("Ingresar Datos Cliente");
        jmIngresarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIngresarClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmIngresarClientes);

        jmeModificarClientes.setText("Modificar Datos Cliente");
        jmeModificarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmeModificarClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmeModificarClientes);

        jmbGestionarSolicitudes.add(jMenu1);

        jMenu2.setText("Reservas");

        jmIngresarReservas.setText("Ingresar Reserva de Arriendo");
        jmIngresarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIngresarReservasActionPerformed(evt);
            }
        });
        jMenu2.add(jmIngresarReservas);

        jmiModificarReservas.setText("Modificar Reserva de Arriendo");
        jmiModificarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarReservasActionPerformed(evt);
            }
        });
        jMenu2.add(jmiModificarReservas);

        jmbGestionarSolicitudes.add(jMenu2);

        jMenu7.setText("Generar Contratos");

        jmCrearContratos.setText("Crear Contrato de Arriendo");
        jmCrearContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearContratosActionPerformed(evt);
            }
        });
        jMenu7.add(jmCrearContratos);

        jmbGestionarSolicitudes.add(jMenu7);

        jMenu4.setText("Gestionar Presupuestos");

        jmiCalcularPresupuesto.setText("Calcular Presupuesto");
        jmiCalcularPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCalcularPresupuestoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiCalcularPresupuesto);

        jmbGestionarSolicitudes.add(jMenu4);

        jMenuBar1.add(jmbGestionarSolicitudes);

        jMenu5.setText("Consultas");

        jmConsultarRegistros.setText("Consultar Registros Clientes");
        jmConsultarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarRegistrosActionPerformed(evt);
            }
        });
        jMenu5.add(jmConsultarRegistros);

        jMenuItem2.setText("Consultar Por R.U.T");
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Parametros");

        jMenuItem1.setText("Gestionar Comunas");
        jMenu3.add(jMenuItem1);

        jMenuItem4.setText("Gestionar Vehículos");
        jMenu3.add(jMenuItem4);

        jMenuItem10.setText("Gestionar Formas Pago");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jmbSalir.setText("Salir");

        jmFinalizar.setText("Finalizar");
        jmFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFinalizarActionPerformed(evt);
            }
        });
        jmbSalir.add(jmFinalizar);

        jMenuBar1.add(jmbSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(475, 238));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmIngresarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIngresarClientesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ic=new IngresoClientes(1);
        ic.setVisible(true);
    }//GEN-LAST:event_jmIngresarClientesActionPerformed

    private void jmFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFinalizarActionPerformed
        // TODO add your handling code here:
        opcion=0;
        opcion=JOptionPane.showConfirmDialog(this,
                "¿Desea salir de la Aplicación?",
                "Salir de la Aplicación",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
         if(opcion==JOptionPane.YES_OPTION)
         {
             System.exit(0);
         }
        
    }//GEN-LAST:event_jmFinalizarActionPerformed

    private void jmeModificarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmeModificarClientesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ic = new IngresoClientes(2);
        ic.setVisible(true);
    }//GEN-LAST:event_jmeModificarClientesActionPerformed

    private void jmIngresarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIngresarReservasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        sa = new SolicitudArriendo(1);
        sa.setVisible(true);
    }//GEN-LAST:event_jmIngresarReservasActionPerformed

    private void jmiModificarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarReservasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        sa = new SolicitudArriendo(2);
        sa.setVisible(true);
    }//GEN-LAST:event_jmiModificarReservasActionPerformed

    private void jmCrearContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearContratosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        con = new Contrato(1);
        con.setVisible(true);
    }//GEN-LAST:event_jmCrearContratosActionPerformed

    private void jmiCalcularPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCalcularPresupuestoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pres = new Presupuesto(1);
        pres.setVisible(true);
    }//GEN-LAST:event_jmiCalcularPresupuestoActionPerformed

    private void jmConsultarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarRegistrosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        lc = new ListadoClientes(1);
        lc.setVisible(true);
    }//GEN-LAST:event_jmConsultarRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorPer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmConsultarRegistros;
    private javax.swing.JMenuItem jmCrearContratos;
    private javax.swing.JMenuItem jmFinalizar;
    private javax.swing.JMenuItem jmIngresarClientes;
    private javax.swing.JMenuItem jmIngresarReservas;
    private javax.swing.JMenu jmbGestionarSolicitudes;
    private javax.swing.JMenu jmbSalir;
    private javax.swing.JMenuItem jmeModificarClientes;
    private javax.swing.JMenuItem jmiCalcularPresupuesto;
    private javax.swing.JMenuItem jmiModificarReservas;
    // End of variables declaration//GEN-END:variables
}
